### ISSUE TITLE
It is possible to release with older glibc version? 

### ISSUE THREAD

**Issue by gccore** [Aseman-Land/Tricks#2]
We have to rebuild the entire platform on older OSs like Debian Stable.

**Comment by realbardia** [comment]
Sure... What version of the Debian you use? 10 or 11?

**Comment by gccore** [comment]
Thank you, it's Debian 10, Buster. With: `Debian GLIBC 2.28-10+deb10u1`

**Comment by realbardia** [comment]
Fixed.
Last AppImage, built using debian buster:
https://tricks.aseman.io/tricks/static/downloads/Tricks-1.0.0_linux.AppImage
