### ISSUE TITLE
The popup text is blur

### ISSUE THREAD

**Issue by gccore** [Aseman-Land/Tricks#3]
![image](https://user-images.githubusercontent.com/107760615/183256137-6db50c5e-6aec-4fde-804b-df2a08df24a6.png) 

---
My previous problem with the graphic card in ImGUI also could be helpful:
- https://github.com/ocornut/imgui/issues/5127

My environment:
- **OS**: Debian 10 buster, Linux 4.19.0-21-amd64.
- **DE**: KDE 5.54.0, Plasma 5.14.5, KWin.
- **GPU**: 
    - **Graphic**: nVidia GT218M (NVS 3100M)
    - **Driver**: nouveau
    - **Capabilities**: 
        - pmmsi 
        - pciexpress 
        - vga_controller
        -  bus_master 
        - cap_list
        -  rom
- **Qt**: 5.15.2
- **QMake**: 3.1
- **Compiler**: Clang 16.0.0
- **Build Type**:
    - QtAseman: 
        - **Commit**: [3963410626a350c8184cca52047903478d50e654](https://github.com/Aseman-Land/QtAseman/commit/3963410626a350c8184cca52047903478d50e654)
        - **Build Type**: Debug
    - Tricks:
        - **Commit**: [7fdaa46ef61505a2d9bf7f3fedad8ac54dd68110](https://github.com/Aseman-Land/Tricks/commit/7fdaa46ef61505a2d9bf7f3fedad8ac54dd68110)
        - **Build Type:** Debug

**Comment by realbardia** [comment]
It seems it's QtAseman popups bug on the some platforms. Thank you for reporting. We'll fix it on the QtAseman soon.

**Comment by realbardia** [comment]
Fixed. It was QtAseman's bug.
https://github.com/Aseman-Land/QtAseman/commit/9dbc12608a886b99ea0fec60d94bfd0b31e1fd1d
